<?php

/* custom routes generated by CRUD */
Route::group(array('prefix' => 'admin'), function () {Route::resource('menus', 'MenusController');
	Route::post('menus/save', array('as' => 'admin.menu.save', 'uses' => 'MenusController@save'));
	Route::get('menus/{id}/delete', array('as' => 'admin.menus.delete', 'uses' => 'MenusController@getDelete'));
	Route::get('menus/{id}/confirm-delete', array('as' => 'admin.menus.confirm-delete', 'uses' => 'MenusController@getModalDelete'));
});Route::group(array('prefix' => 'admin'), function () {Route::resource('menu1s', 'Menu1sController');
	Route::get('menu1s/{id}/delete', array('as' => 'admin.menu1s.delete', 'uses' => 'Menu1sController@getDelete'));
	Route::get('menu1s/{id}/confirm-delete', array('as' => 'admin.menu1s.confirm-delete', 'uses' => 'Menu1sController@getModalDelete'));
});